clickhouse:
  target: clickhouse
  outputs:    
    clickhouse:
      type: clickhouse
      host: "{{ env_var('CLICKHOUSE_HOST') }}"
      user: "{{ env_var('CLICKHOUSE_USER') }}"
      password: "{{ env_var('CLICKHOUSE_PASSWORD') }}"
      port: "{{ env_var('CLICKHOUSE_PORT') | int }}"
      database: public
      schema: public
      threads: 4