name: minerva_postgres_dbt
version: '1.0'
config-version: 2
profile: postgres

model-paths: ["models"]

models:
  minerva_postgres_dbt:
    match_performance_mart:
      +schema: match_performance_mart
    player_performance_mart:
      +schema: player_performance_mart
    team_standings_mart:
      +schema: team_standings_mart
